### ISSUE TITLE
regex compilation errors when building on summit

### ISSUE THREAD

**Issue by petermcLBL** [spiral-software/fftx#9]
I am running on summit, with
cmake version 3.18.2
gcc (GCC) 7.4.0
Cuda compilation tools, release 9.2, V9.2.148

I can build Spiral.  When I try to build fftx, this works:
cmake -D_codegen=GPU ..

But then the next step fails:

make install
[  1%] Building CXX object examples/test_plan_dft/CMakeFiles/test_plan_dft.mddft.fftx.driver.dir/mddft.fftx.cpp.o
In file included from /ccs/home/petermc/fftx/examples/test_plan_dft/mddft.fftx.cpp:3:0:
/ccs/home/petermc/fftx/include/fftx3.hpp: In function 'void fftx::closeDAG(std::array<fftx::array_t<DIM, T>, COUNT>&, const char*)':
/ccs/home/petermc/fftx/include/fftx3.hpp:430:88: error: no matching function for call to 'regex_replace(const char*&, std::regex, const char*&)'
    std::string header_text = std::regex_replace(header_template,std::regex("PLAN"),name);
                                                                                        ^
/ccs/home/petermc/fftx/include/fftx3.hpp:430:88: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from /ccs/home/petermc/fftx/include/fftx3.hpp:17,
                 from /ccs/home/petermc/fftx/examples/test_plan_dft/mddft.fftx.cpp:3:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
In file included from /ccs/home/petermc/fftx/examples/test_plan_dft/mddft.fftx.cpp:3:0:
/ccs/home/petermc/fftx/include/fftx3.hpp:430:88: note:   deduced conflicting types for parameter '_Bi_iter' ('std::basic_regex<char>' and 'const char*')
    std::string header_text = std::regex_replace(header_template,std::regex("PLAN"),name);
                                                                                        ^
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from /ccs/home/petermc/fftx/include/fftx3.hpp:17,
                 from /ccs/home/petermc/fftx/examples/test_plan_dft/mddft.fftx.cpp:3:
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
In file included from /ccs/home/petermc/fftx/examples/test_plan_dft/mddft.fftx.cpp:3:0:
/ccs/home/petermc/fftx/include/fftx3.hpp:430:88: note:   mismatched types 'const std::basic_string<_Ch_type>' and 'const char*'
    std::string header_text = std::regex_replace(header_template,std::regex("PLAN"),name);
                                                                                        ^
/ccs/home/petermc/fftx/include/fftx3.hpp: In function 'void fftx::closeScalarDAG(std::array<fftx::array_t<DIM, T>, COUNT>&, const char*)':
/ccs/home/petermc/fftx/include/fftx3.hpp:516:88: error: no matching function for call to 'regex_replace(const char*&, std::regex, const char*&)'
    std::string header_text = std::regex_replace(header_template,std::regex("PLAN"),name);
                                                                                        ^
/ccs/home/petermc/fftx/include/fftx3.hpp:516:88: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from /ccs/home/petermc/fftx/include/fftx3.hpp:17,
                 from /ccs/home/petermc/fftx/examples/test_plan_dft/mddft.fftx.cpp:3:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
In file included from /ccs/home/petermc/fftx/examples/test_plan_dft/mddft.fftx.cpp:3:0:
/ccs/home/petermc/fftx/include/fftx3.hpp:516:88: note:   deduced conflicting types for parameter '_Bi_iter' ('std::basic_regex<char>' and 'const char*')
    std::string header_text = std::regex_replace(header_template,std::regex("PLAN"),name);
                                                                                        ^
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from /ccs/home/petermc/fftx/include/fftx3.hpp:17,
                 from /ccs/home/petermc/fftx/examples/test_plan_dft/mddft.fftx.cpp:3:
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
In file included from /ccs/home/petermc/fftx/examples/test_plan_dft/mddft.fftx.cpp:3:0:
/ccs/home/petermc/fftx/include/fftx3.hpp:516:88: note:   mismatched types 'const std::basic_string<_Ch_type>' and 'const char*'
    std::string header_text = std::regex_replace(header_template,std::regex("PLAN"),name);
                                                                                        ^
make[2]: *** [examples/test_plan_dft/CMakeFiles/test_plan_dft.mddft.fftx.driver.dir/mddft.fftx.cpp.o] Error 1
make[1]: *** [examples/test_plan_dft/CMakeFiles/test_plan_dft.mddft.fftx.driver.dir/all] Error 2
make: *** [all] Error 2

**Comment by broderickpt** [comment]
There is no issue with FFTX.

CMake has actually found gcc version 4.8 (the version of gcc cmake uses when building is emitted as one of the first lines when running cmake; further it is recorded in CMakeCache.txt in the build directory).  The errors occur because gcc 4.8 is too old to support C/C++ standard 14 as requested in the make files.

I have found that on summit I need to set environment variable CC and CXX to point to the specific compiler.  For example, the following build environment works as expected (later versions of gcc & CUDA also work):

cmake version 3.18.2
gcc (GCC) 7.4.0
Cuda compilation tools, release 9.2, V9.2.148

**and add**
export CC=/sw/summit/gcc/7.4.0/bin/gcc
export CXX=/sw/summit/gcc/7.4.0/bin/g++

**Comment by petermcLBL** [comment]
That worked, with
`module load cmake gcc/7.4.0 cuda/9.2.148`
As you noted, the default version of module gcc is 6.4.0, and 7.4.0 is required.
But the default version of module cuda is 10.1.243, and it does not work with that version. I had to use the older version 9.2.148 as you suggested. The newest version of module cuda is 11.2.0.

**Comment by broderickpt** [comment]
I generally try to use recent or latest versions when feasible.

It all works with gcc/9.1.0 and cuda/11.2.0

**Comment by petermcLBL** [comment]
I find that when I put "module load cuda/11.2.0" in the script I send
to bsub on summit, it tells me:
The following have been reloaded with a version change:
  1) cuda/11.2.0 => cuda/9.2.148
I find that the highest version of the cuda module that I can put in
the script without getting this reload is 10.2.89.

But I get no output in any case.  I have:
jsrun -n1 -a1 -g1 ~/fftx/build/bin/testmddft > testmddft.out

And it runs:
Started at Mon Mar  1 20:03:14 2021
Terminated at Mon Mar  1 20:03:32 2021

But when I look at testmddft.out, it is empty.

When you run on summit, do you see output?

**Comment by petermcLBL** [comment]
Now I am able to get test_plan_dft to produce output on summit.
The trick was to load modules with run-time libraries before jsrun:
module load gcc/9.1.0 cuda/10.2.89
